package com.stoyanvuchev.systemuibarstweaker.demo.presentation.common.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006972)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF8CF2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F23)
val md_theme_light_secondary = Color(0xFF4A6366)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE7EB)
val md_theme_light_onSecondaryContainer = Color(0xFF051F22)
val md_theme_light_tertiary = Color(0xFF515E7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF0C1B36)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFD)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF4ED8E8)
val md_theme_light_surfaceTint = Color(0xFF006972)
val md_theme_light_outlineVariant = Color(0xFFBEC8CA)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFF8FAFA)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDAE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)

val md_theme_dark_primary = Color(0xFF4ED8E8)
val md_theme_dark_onPrimary = Color(0xFF00363C)
val md_theme_dark_primaryContainer = Color(0xFF004F56)
val md_theme_dark_onPrimaryContainer = Color(0xFF8CF2FF)
val md_theme_dark_secondary = Color(0xFFB1CBCF)
val md_theme_dark_onSecondary = Color(0xFF1C3437)
val md_theme_dark_secondaryContainer = Color(0xFF324B4E)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7EB)
val md_theme_dark_tertiary = Color(0xFFB9C6EA)
val md_theme_dark_onTertiary = Color(0xFF23304D)
val md_theme_dark_tertiaryContainer = Color(0xFF394664)
val md_theme_dark_onTertiaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE0E3E3)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E3)
val md_theme_dark_inversePrimary = Color(0xFF006972)
val md_theme_dark_surfaceTint = Color(0xFF4ED8E8)
val md_theme_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF101414)
val md_theme_dark_onSurface = Color(0xFFC4C7C7)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8CA)


// val seed = Color(0xFF0D7680)